//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class practicEntities : DbContext
    {

        private static practicEntities _context;
        public practicEntities()
            : base("name=practicEntities")
        {
        }
        public static practicEntities GetContext()
        {
            if (_context == null)
                _context = new practicEntities();

            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<punkt> punkt { get; set; }
        public virtual DbSet<tovar> tovar { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<zakaz> zakaz { get; set; }
    }
}
